### ISSUE TITLE
Fix netlify

### ISSUE THREAD

**Issue by rjoleary** [linuxboot/book#22]
Netlify has been broken on all the pull requests

**Comment by orangecms** [comment]
Is that still integrated? I don't see it in current PRs. It would be great to have some build (I mean, besides just browsing here on GitHub). Maybe even on linuxboot.org directly, making #31 obsolete?

With my local copy, I have simply `cat`ted and piped all the files into Pandoc to get a PDF, with a little `sed` for escaping. It could as well output HTML. There is also the option of using Sphinx, like coreboot does for doc.coreboot.org. I'd be willing to contribute either setup. Any thoughts on that?

**Comment by rjoleary** [comment]
It looks like our netlify no longer exists. The plan was to put it at the subdomain book.linuxboot.org
It doesn't have to be netlify. There are other options like github books, etc..

I like the idea of using pandoc to create a pdf.

For the website, I'd like to see something more dynamic, like with a table of contents on the sidebar like what you see in the netlify docs: https://docs.netlify.com/site-deploys/create-deploys/#netlify-cli

Please feel free to contribute. I don't think anyone else is working on it. Contributions are very welcome!

**Comment by orangecms** [comment]
Note: We have moved to GitHub pages.

Maybe create a new issue for creating a PDF as a release artifact.
GitHub Workflows can do that for us and publish to /releases.
