### ISSUE TITLE
Update u-root URL

### ISSUE THREAD

**Issue by therandomsecurityguy** [linuxboot/book#57]
URL for u-root in the [README](https://github.com/linuxboot/book/blob/master/coreboot.u-root.systemboot/README.md) points to https://u-root.tk/. Should point to https://github.com/u-root/u-root.

I can submit a PR if that's easier.

**Comment by orangecms** [comment]
resolved via 2437f49b0f956bdec977ff8b8c3844d794183f1c long ago :D thank you!
