### ISSUE TITLE
rework setup for book deployment

### ISSUE THREAD

**Issue by orangecms** [linuxboot/book#82]
We are currently using plain GitHub pages, which is rather simple, but missing essential features such as navigation from chapters.

There are modern tools that integrate with GitHub.
For the LinuxBoot website, we are currently using Hugo.

For the book, this looks like a promising option, being used for multiple books in the Rust ecosystem already: https://github.com/rust-lang/mdBook

**Comment by orangecms** [comment]
https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions

**Comment by pamolloy** [comment]
@orangecms looks like this was resolved in #83 and can be closed
